#!/usr/bin/env python3
"""Generate the machine-readable catalog and human-readable index of skills.

Outputs:
    catalog.json  — every skill's metadata + path, for tooling / search / agents.
    INDEX.md      — grouped tables with red<->blue pairings, for humans.

Run after adding or changing a skill. CI runs this with --check to fail the
build if the committed artifacts are stale.

Usage:
    python tools/build_catalog.py [--check]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate import load_frontmatter  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
SKILLS = REPO / "skills"
CATALOG_JSON = REPO / "catalog.json"
INDEX_MD = REPO / "INDEX.md"

TEAM_BADGE = {"red": "🔴 red", "blue": "🔵 blue", "purple": "🟣 purple"}


def collect() -> list[dict]:
    rows = []
    for path in sorted(SKILLS.rglob("SKILL.md")):
        fm, _body, errors = load_frontmatter(path)
        if fm is None:
            continue
        rows.append({
            "name": fm.get("name"),
            "description": " ".join(str(fm.get("description", "")).split()),
            "team": fm.get("team"),
            "app_type": fm.get("app_type"),
            "stage": (fm.get("killchain") or {}).get("stage"),
            "techniques": fm.get("techniques") or {},
            "pairs_with": fm.get("pairs_with") or [],
            "risk": (fm.get("risk") or {}).get("level"),
            "authorization": fm.get("authorization"),
            "maturity": fm.get("maturity"),
            "version": fm.get("version"),
            "path": str(path.relative_to(REPO)),
        })
    return rows


def render_catalog_json(rows: list[dict]) -> str:
    doc = {
        "schema": "redblueskills/catalog/v1",
        "count": len(rows),
        "skills": rows,
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def render_index_md(rows: list[dict]) -> str:
    by_app: dict[str, list[dict]] = {}
    for r in rows:
        by_app.setdefault(r["app_type"] or "unknown", []).append(r)

    out = [
        "<!-- GENERATED BY tools/build_catalog.py — DO NOT EDIT BY HAND -->",
        "# Skill index",
        "",
        f"{len(rows)} skill(s). Regenerate with `make catalog`.",
        "",
        "| Legend | |",
        "|---|---|",
        "| 🔴 red | offensive |",
        "| 🔵 blue | defensive |",
        "| 🟣 purple | joint |",
        "",
    ]
    for app in sorted(by_app):
        out.append(f"## {app}")
        out.append("")
        out.append("| Skill | Team | Stage | ATT&CK | Risk | Maturity | Paired with |")
        out.append("|---|---|---|---|---|---|---|")
        for r in sorted(by_app[app], key=lambda x: (x["team"] or "", x["stage"] or "", x["name"] or "")):
            attack = ", ".join((r["techniques"] or {}).get("attack") or []) or "—"
            pairs = ", ".join(f"`{p}`" for p in r["pairs_with"]) or "—"
            link = f"[`{r['name']}`]({r['path']})"
            out.append(
                f"| {link} | {TEAM_BADGE.get(r['team'], r['team'])} | {r['stage']} "
                f"| {attack} | {r['risk']} | {r['maturity']} | {pairs} |"
            )
        out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail if committed artifacts differ from freshly generated ones")
    args = ap.parse_args()

    rows = collect()
    catalog = render_catalog_json(rows)
    index = render_index_md(rows)

    if args.check:
        stale = []
        if not CATALOG_JSON.exists() or CATALOG_JSON.read_text(encoding="utf-8") != catalog:
            stale.append("catalog.json")
        if not INDEX_MD.exists() or INDEX_MD.read_text(encoding="utf-8") != index:
            stale.append("INDEX.md")
        if stale:
            print(f"STALE: {', '.join(stale)} out of date — run `make catalog`", file=sys.stderr)
            return 1
        print("catalog artifacts are up to date")
        return 0

    CATALOG_JSON.write_text(catalog, encoding="utf-8")
    INDEX_MD.write_text(index, encoding="utf-8")
    print(f"wrote catalog.json and INDEX.md ({len(rows)} skills)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
